### ISSUE TITLE
Not taking in new user

### ISSUE THREAD

**Issue by AkhileshManda** [s2ke4/DoubtBin#1]
I installed the app using the apk but when I try signing in with google it just returns to the home screen

**Comment by keshavagarwal17** [comment]
can you please share the screenshot of your screen after signing in with google, because it is working fine on our devices

**Comment by AkhileshManda** [comment]
![WhatsApp Image 2021-04-18 at 14 27 44](https://user-images.githubusercontent.com/70640191/115140610-c1432700-a055-11eb-98dd-b7e25b326fb9.jpeg)
![WhatsApp Image 2021-04-18 at 14 27 44 (1)](https://user-images.githubusercontent.com/70640191/115140613-c2745400-a055-11eb-8147-f6f1533f8079.jpeg)
![WhatsApp Image 2021-04-18 at 14 27 44 (2)](https://user-images.githubusercontent.com/70640191/115140620-c3a58100-a055-11eb-8126-6221f5b3e578.jpeg)

**Comment by AkhileshManda** [comment]
![image](https://user-images.githubusercontent.com/70640191/115140903-3a8f4980-a057-11eb-8197-8a802ab2f67e.png)
this came when i ran it via android studio....(all warnings , no erros) I thought it might help

**Comment by darshanhande11** [comment]
@AkhileshManda If u want to use the application as a user, then you can directly go to the drive link and download the apk file.
If u just clone the repo and try to run it, then you won't be able to connect to the backend.
You can download the apk from [here](https://drive.google.com/file/d/1JqUDhpj9IzZAeg3OFpdQERST412y-mcT/view?usp=sharing)

**Comment by AkhileshManda** [comment]
I did. Let me try uninstalling and reinstalling

**Comment by AkhileshManda** [comment]
It worked..Thanks!
